# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Piero's Portfolio"
description: "Lima, Peru. Personal site, built while learning data and web development."
author:      "Gilmar"
